# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh StorageClass

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-encrypted-retained
provisioner: kubernetes.io/azure-disk
volumeBindingMode: Immediate
reclaimPolicy: Retain  # Useful in case you delete the PersistentVolumeClaim
